__author__ = 'Lai Tash (lai.tash@yandex.ru)'

MOD_NEG = 0x80000000
MOD_THIS_OR_NEXT = 0x40000000
MOD_ALL = MOD_NEG | MOD_THIS_OR_NEXT

OPC_ENDTRY = 3
OPC_TRYBEGIN = 4
OPC_ELSETRY = 5
OPC_TRYFORRANGE = 6
OPC_TRYFORRANGE_BACK = 7
OPC_BLOCK = (OPC_TRYBEGIN, OPC_TRYFORRANGE, OPC_TRYFORRANGE_BACK)

TAG_REGISTER = 1
OP_NUM_VALUE_BITS = 56
OPMASK_REGISTER = TAG_REGISTER << OP_NUM_VALUE_BITS

OTYPE_PLAIN = 0
OTYPE_INT_REG = 1

BT_PLAIN = 0
BT_TRY = 1
BT_TRYFORWARD = 2
BT_TRYBACK = 3
BT_SCRIPT  = 4
BT_HAS_ENDTRY = (BT_TRY, BT_TRYBACK, BT_TRYFORWARD)
